# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: fytinnovations.storemanagement::lang.categories.reorder

# Attribute name
nameFrom: name

# Model Class name
modelClass: Fytinnovations\StoreManagement\Models\Category

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar